swagger: "2.0"
info:
  description: "Set of feasible operations for the entity task"
  version: "0.0.1"
  title: "TODO LIST APP"
host: "localhost:5001"
basePath: "/"
tags:
- name: "tasks"
  description: "All the accesible information of the entity task"

schemes:
- "http"
paths:
  /tasks/:
    get:
      tags:
      - "tasks"
      summary: "Retrieves all tasks"
      description: "Retrieves all tasks"
      operationId: "getAllTasks"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
        400:
          description: "Bad request"
        404:
          description: "Not found"
  /tasks/{identifier}:
    post:
      tags:
      - "tasks"
      summary: "Add a new task to the todo list"
      description: "Add a new task to the todo list"
      operationId: "addTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "identifier"
        description: "ID of the task to create"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Task object that will be added"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        400:
          description: "Bad request"
        500:
          description: "Internal error"
        201:
          description: "Created"
    put:
      tags:
      - "tasks"
      summary: "Update an existing task"
      description: "Update an existing task"
      operationId: "updateTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "identifier"
        description: "ID of the task to create"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Task object that will be updated"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        400:
          description: "Bad request"
        500:
          description: "Internal error"
        201:
          description: "Created"
    get:
      tags:
      - "tasks"
      summary: "Retrieves a task based on the provided Id"
      description: "Retrieves a task based on the provided Id"
      operationId: "getTask"
      produces:
      - "application/json"
      parameters:
      - name: "identifier"
        in: "path"
        type: "integer"
        format: "int64"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
        400:
          description: "Bad request"
        404:
          description: "Not found"
    delete:
      tags:
      - "tasks"
      summary: "Deletes a task based on the provided Id"
      description: "Deletes a task based on the provided Id"
      operationId: "deleteTask"
      produces:
      - "application/json"
      parameters:
      - name: "identifier"
        in: "path"
        type: "integer"
        format: "int64"
        required: true
      responses:
        200:
          description: "Success"
        400:
          description: "Bad request"
        404:
          description: "Not found"
  
definitions:
  Task:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "Task name"
      status:
        type: "string"
        example: "Completed"
      date_start:
        type: "string"
        example: "31-12-2019"
      date_end:
        type: "string"
        example: "31-12-2019"
